update actions

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -27,7 +27,7 @@ jobs:
       run: |
         sudo apt-get update
         sudo apt -y install libxml2-utils
-    - name: Install dependencies
+    - name: Install Python dependencies
       run: |
         python -m pip install --upgrade pip
         pip install flake8 pytest
@@ -35,10 +35,26 @@ jobs:
     - name: Lint with flake8
       run: |
         # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+        LINT=$(flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics)
+        echo LINT
+        if [[ LINT > 0 ]]; then
+          echo "GO GO"
+        else
+          echo "there are Python syntax errors or undefined names"
+          exit 1
+        fi
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-    - name: Test with pytest
+        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+        LINT=$(flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics)
+        echo LINT
+        if [[ LINT > 0 ]]; then
+          echo "GO GO"
+        else
+          echo "there are Python syntax errors or undefined names"
+          exit 1
+        fi
+    - name: Test and Coverage
       run: |
         coverage run -m pytest
         coverage report -m --omit="*/test*"
@@ -51,5 +67,6 @@ jobs:
           echo "Boa cobertura"
         else
           echo "Cobertura a ser melhorada"
+          exit 1
         fi
 
